name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pandas pyinstaller openpyxl
    
    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed --name "GEMA_TXT_Excel_Converter" --clean --noconfirm konverter_gui.py
    
    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: GEMA_TXT_Excel_Converter
        path: dist/GEMA_TXT_Excel_Converter.exe
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/GEMA_TXT_Excel_Converter.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}